server.port=8080
logging.level.com.valuelab=DEBUG

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

#JDBC Driver: PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
#Setting for connection pool
spring.datasource.hikari.maxLifetime=900000
spring.datasource.hikari.keepaliveTime=30000
spring.datasource.hikari.connectionTestQuery=select case when current_setting('transaction_read_only') = 'off' then 1 else random() / 0 end
spring.datasource.type=com.zaxxer.hikari.HikariDataSource

#Validation messages
spring.messages.basename=messages
spring.messages.cache-duration=-1
spring.messages.encoding=UTF-8

#MyBatis
logging.level.com.valuelab.repository=DEBUG
logging.level.org.springframework=WARN
mybatis.type-aliases-package=com.valuelab.entity
mybatis.mapper-locations=classpath*:/com.valuelab.repository
mybatis.configuration.map-underscore-to-camel-case=true

# aws cognito
cognito.clientId=${COGNITO_CLIENT_ID}
cognito.userPoolId=${COGNITO_USER_POOL_ID}
cognito.issuer.url=${COGNITO_ISSUER_URL}

# aws
# cloud.aws.region.static=${AWS_REGION}

# Spring Batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

#for s3
# s3.bucketname=${AWS_S3_BUCKET_NAME}
# s3.foldername=export

#for Actuator
management.endpoints.web.exposure.include=prometheus
